# This workflow will run build using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Tests

on:
  push:
  workflow_call: # workflow can be called by another workflow
  workflow_dispatch: # workflow can be called manually

jobs:

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Read vars
        run: |
          cat <<EOF > test/vars.ts
          ${{ secrets.VARS }}
          EOF
      - run: npm install
      - name: Run tests for Node.js
        run: npm test

  test_browser:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Read vars
        run: |
          cat <<EOF > test/vars.ts
          ${{ secrets.VARS }}
          EOF
      - run: npm install
      - name: Run tests for browser
        run: npm run test:browser